# Generated by Django 4.0.2 on 2022-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Visitor Name')),
                ('person_to_see', models.CharField(max_length=100, verbose_name='Person Visited')),
                ('telephone', models.CharField(max_length=100, verbose_name='Visitor Telephone')),
                ('purpose', models.CharField(max_length=100, verbose_name='Purpose of Visit')),
                ('images_collected', models.TextField(verbose_name='Base64 Encodings')),
            ],
        ),
    ]
